services:
  web:
    build: .
    image: farmer_management-web:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DEBUG=1
    depends_on:
      - redis
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - farmer_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - farmer_network
  celery:
    image: farmer_management-web:latest
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - web
      - redis
    command: celery -A farmer_management worker -l info
    networks:
      - farmer_network
  celery-beat:
    image: farmer_management-web:latest
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - web
      - redis
    command: celery -A farmer_management beat -l info
    networks:
      - farmer_network
networks:
  farmer_network:
    driver: bridge