# Generated by Django 5.0.6 on 2025-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_images/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, default='farmer_images/default.jpg', null=True, upload_to='farmer_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='user_images/'),
        ),
    ]
