# Generated by Django 5.0.6 on 2025-03-18 12:04

import farmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmer_aadhar_image_farmer_image_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_id',
            field=models.CharField(help_text='Enter a 12-digit numeric Aadhar ID.', max_length=12, unique=True, validators=[farmers.models.validate_aadhar_id]),
        ),
    ]
