# Generated by Django 5.0.6 on 2025-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmer_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
